version: "3.2"
services:
  rabbitmq:
    build: ./rabbitmqgo
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net 
 #   healthcheck:
 #       test: ["CMD", "curl", "-f", "http://rabbitmq:5672"]
 #       interval: 30s
 #       timeout: 10s
 #       retries: 5

  crawler:
    build: .
    ports:
      - 5050:5050
    networks:
      - rabbitmq_go_net
    restart: on-failure
 #   depends_on:
 #     - rabbitmq
 #   links: 
 #     - rabbitmq

networks:
  rabbitmq_go_net:
    driver: bridge