version: "3.2"
services:
  rabbitmq:
    build: ./rabbitmqgo
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net 

  crawler:
    build: .
    ports:
      - 5050:5050
    networks:
      - rabbitmq_go_net
    restart: on-failure

  elastic:
    image: elasticsearch:8.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
    networks:
      - rabbitmq_go_net  


networks:
  rabbitmq_go_net:
    driver: bridge