version: "3.2"
services:
  rabbitmq:
    build: ./res/rabbitmqgo
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net 

  crawler:
    build:
      context: .
      dockerfile: ./cmd/crawler/Dockerfile
    ports:
      - 5050:5050
    networks:
      - rabbitmq_go_net
    restart: on-failure
    volumes:
      - ./logs/crawler:/logs

  analyzer:
    build:
      context: .
      dockerfile: ./cmd/analyzer/Dockerfile
    networks:
      - rabbitmq_go_net
    restart: on-failure
    volumes:
      - ./logs/analyzer:/logs

  elasticsearch:
    container_name: es-container
    image: elasticsearch:7.17.9
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - rabbitmq_go_net
    ports:
      - 9200:9200
      - 9300:9300


networks:
  rabbitmq_go_net:
    driver: bridge